### ISSUE TITLE
Touch control behaves strange when yaw is negative

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-android-client#63]
The problem seems to be related to yaw control only and when it is more then -100. Then the tough screen controls "flickers/jumps" and the yaw is reset to 0. If I limit the yaw to 99 the problem is gone.

Phone: Galaxy S6
Android: 6.0.1

**Comment by fredg02** [comment]
I can't reproduce this bug with a Nexus 5x running Android 6.0.1. Can you reproduce it on any other phone?

**Comment by krichardsson** [comment]
I have the same (or similar) problem on my Sony Xperia Z3 (D5803), Android 6.0.1.
For me it happens when the left touch pad/joystick (regardless of flight mode) is moved left further than -99. The application semi-freezes for a few seconds and then resizes the touch pads and makes them slightly smaller (!). After this they do not really work at all and the behavior is erratic.
